name: Run linter checks

# The aim here is to keep the code in the right style. We only "target" `src` folder files as they are technically the only
# non configuration files (and have issues maintaining otherwise).
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  linter-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        uses: cpp-linter/cpp-linter-action@v2
        with:
          style: file
